Repository Solvro/backend-topwr, pull requests merged in 2025-06, with the labels that each got.

#183 feat: university newsfeed
  app/controllers/newsfeed_controller.ts
  app/exceptions/http_exceptions.ts
  app/services/newsfeed_service.ts
  package-lock.json
  package.json
  start/routes.ts
Labels: size/L

#194 feat(validators): luxonDateTime validator model
  adonisrc.ts
  app/decorators/typed_model.ts
  app/validators/luxon_datetime.ts
  start/kernel.ts
Labels: size/L

#189 feat: event calendar
  app/controllers/event_calendar_controller.ts
  app/models/calendar_event.ts
  app/utils/ics.ts
  database/migrations/1749631863474_create_calendar_events_table.ts
  database/scrapers/event_calendar.ts
  start/routes.ts
Labels: size/XL

#197 ci: quickfix command for PRs
  .github/workflows/pr_commands.yml
  package.json
Labels: size/M
