Repository Solvro/backend-topwr, pull requests merged in 2025-03, with the labels that each got.

#117 feat(admin panel): add solvro branding and minor facelifting
  adonisrc.ts
  app/admin/auth.ts
  app/admin/branding.ts
  app/admin/component_loader.ts
  app/admin/components/dashboard.tsx
  app/admin/locale.ts
  app/admin/resources/about_us.ts
  app/admin/resources/academic_calendars.ts
  app/admin/resources/admin_panel.ts
  app/admin/resources/buildings.ts
  app/admin/resources/departments.ts
  app/admin/resources/guides.ts
  app/admin/resources/index.ts
  app/admin/resources/student_organizations.ts
  app/admin/resources/utils/timestamps.ts
  app/admin/resources/versions.ts
  config/adminjs.ts
  config/static.ts
  eslint.config.js
  package-lock.json
  package.json
  public/main.css
  public/topwr_logo.ico
  start/kernel.ts
  tsconfig.json
Labels: size/XL

#118 fix: add sequence fixing in buildings scraper
  database/scrapers/buildings.ts
Labels: size/XS

#122 ci: add a Dockerfile build workflow
  .github/workflows/docker.yml
Labels: size/S

#114 feat: organizations scripts
  app/models/student_organization.ts
  database/migrations/1733672331665_create_student_organizations_table.ts
  database/scrapers/organizations.ts
Labels: size/L

#125 docs: add basic API documentation to readme
  README.md
Labels: size/L

#98 feat: create faq script to migrate the data
  database/scrapers/faq.ts
Labels: size/L

#123 refactor(fileService): save info about stored files in the database
  app/controllers/files_controller.ts
  app/exceptions/file_service_errors.ts
  app/models/file_entry.ts
  app/services/files_service.ts
  database/migrations/1741334906365_create_file_entries_table.ts
  database/scrapers/buildings.ts
  database/scrapers/contributors.ts
  database/scrapers/departments.ts
  database/scrapers/faq.ts
  database/scrapers/organizations.ts
  database/seeders/about_us_seeder.ts
Labels: size/L

#129 feat(AdminPanel): add photo_dropbox component
  app/admin/component_loader.ts
  app/admin/components/photo_dropbox.tsx
Labels: size/M

#130 refactor(admin panel): uploading photos and resource creation
  app/admin/component_loader.ts
  app/admin/components/photo_display.tsx
  app/admin/components/photo_dropbox.tsx
  app/admin/resources/about_us.ts
  app/admin/resources/academic_calendars.ts
  app/admin/resources/admin_panel.ts
  app/admin/resources/buildings.ts
  app/admin/resources/departments.ts
  app/admin/resources/guides.ts
  app/admin/resources/index.ts
  app/admin/resources/resource_factory.ts
  app/admin/resources/resource_index.ts
  app/admin/resources/resource_registers/about_us.ts
  app/admin/resources/resource_registers/academic_calendars.ts
  app/admin/resources/resource_registers/admin_panel.ts
  app/admin/resources/resource_registers/buildings.ts
  app/admin/resources/resource_registers/departments.ts
  app/admin/resources/resource_registers/guides.ts
  app/admin/resources/resource_registers/student_organizations.ts
  app/admin/resources/resource_registers/versions.ts
  app/admin/resources/student_organizations.ts
  app/admin/resources/utils/timestamps.ts
  app/admin/resources/versions.ts
  app/controllers/files_controller.ts
  app/models/building.ts
  config/adminjs.ts
  database/scrapers/buildings.ts
Labels: size/XXL

#112 feat: add command and scraper script for academic calendar
  database/scrapers/academic_calendar_scraper.ts
Labels: size/L

#138 Fix(admin panel): QoL changes
  app/admin/resources/resource_registers/about_us.ts
  app/admin/resources/resource_registers/academic_calendars.ts
  app/admin/resources/resource_registers/departments.ts
  app/admin/resources/resource_registers/student_organizations.ts
  app/admin/resources/resource_registers/versions.ts
  app/controllers/about_us_controller.ts
  app/enums/link_type.ts
  app/enums/organization_status.ts
  app/enums/organization_type.ts
  app/enums/weekday.ts
  app/models/contributor.ts
  app/models/department.ts
  app/models/student_organization.ts
  app/models/student_organization_link.ts
  database/migrations/1743075304168_add_organization_status.ts
  database/migrations/1743076719946_rename_student_organization_links_column.ts
  database/migrations/1743077320344_rename_organization_type_enum.ts
  database/scrapers/organizations.ts
  database/seeders/organization_seeder.ts
Labels: size/L

#142 refactor(controllers): deduplicate controller code
  app/controllers/academic_calendars_controller.ts
  app/controllers/base_controller.ts
  app/controllers/buildings_controller.ts
  app/controllers/campuses_controller.ts
  app/controllers/changes_controller.ts
  app/controllers/contributors_controller.ts
  app/controllers/day_swaps_controller.ts
  app/controllers/departments_controller.ts
  app/controllers/fields_of_studies_controller.ts
  app/controllers/fields_of_study_controller.ts
  app/controllers/guide_articles_controller.ts
  app/controllers/guide_authors_controller.ts
  app/controllers/guide_questions_controller.ts
  app/controllers/holidays_controller.ts
  app/controllers/libraries_controller.ts
  app/controllers/milestones_controller.ts
  app/controllers/roles_controller.ts
  app/controllers/student_organizations_controller.ts
  app/controllers/versions_controller.ts
  app/exceptions/handler.ts
  app/scopes/preload_helper.ts
  app/scopes/search_helper.ts
  app/scopes/sort_helper.ts
  start/routes.ts
Labels: size/XXL

#143 ci: better migration tests
  .github/workflows/db.yml
  .github/workflows/db_pr.yml
  .github/workflows/docker.yml
Labels: size/L
