Repository Solvro/backend-topwr, pull requests merged in 2025-07, with the labels that each got.

#178 feat: cache reference number
  app/admin/resources/resource_index.ts
  app/admin/resources/resource_registers/cache_reference_number.ts
  app/controllers/cache_reference_number_controller.ts
  app/models/cache_reference_number.ts
  database/migrations/1750976914369_create_cache_reference_numbers_table.ts
  database/scrapers/cache_reference_number.ts
  start/routes.ts
Labels: size/L

#200 refactor(buildings): delete building_icon
  app/admin/resources/resource_registers/buildings.ts
  app/enums/building_icon.ts
  app/models/building.ts
  database/migrations/1752089796061_alter_buildings_and_remove_building_icon.ts
  database/scrapers/buildings.ts
  database/seeders/building_seeder.ts
Labels: size/M

#201 refactor(scrapers): make about us a scraper & deduplicate code
  app/enums/link_type.ts
  app/utils/date.ts
  assets/about_us_links.json
  commands/db_scrape.ts
  database/scrapers/about_us.ts
  database/scrapers/academic_calendar.ts
  database/scrapers/buildings.ts
  database/scrapers/contributors.ts
  database/scrapers/departments.ts
  database/scrapers/faq.ts
  database/scrapers/organizations.ts
  database/scrapers/pink_boxes.ts
  database/seeders/about_us_seeder.ts
Labels: size/XL

#209 feat: department distinction field
  app/models/department.ts
  database/migrations/1752572202204_add_is_branch_field_to_departments_table.ts
  database/scrapers/departments.ts
  database/seeders/department_seeder.ts
Labels: size/S

#210 fix: range search
  README.md
  app/scopes/search_helper.ts
Labels: size/L

#217 feat: translator reference cache number
  app/controllers/mobile_config_controller.ts
  app/models/mobile_config.ts
  database/migrations/1753365356028_alter_mobile_configs_table_add_translator_ref_number.ts
  database/scrapers/mobile_config.ts
Labels: size/M
