Repository Solvro/backend-topwr, pull requests merged in 2025-05, with the labels that each got.

#168 feat(admin_panel): validate requests
  app/admin/resources/resource_factory.ts
  app/decorators/typed_model.ts
  app/exceptions/admin_panel_error_reporter.ts
  app/models/aed.ts
  app/models/bicycle_shower.ts
  app/models/building.ts
  app/models/food_spot.ts
  app/models/library.ts
Labels: size/M

#165 feat: pink boxes migration and model
  app/controllers/pink_boxes_controller.ts
  app/models/pink_box.ts
  database/migrations/1745315804369_create_pink_boxes_table.ts
  database/scrapers/departments.ts
  start/routes.ts
Labels: size/L

#171 fix: add weekday enum values to regular hours res
  app/admin/resources/resource_registers/buildings.ts
Labels: size/XS

#172 fix(models): add validators for time fields
  app/models/regular_hour.ts
  app/models/special_hour.ts
  app/validators/time.ts
Labels: size/S

#173 ci: auto-assign PR author if noone was assigned during PR creation
  .github/workflows/pr_automation.yml
Labels: size/S

#175 refactor(models/student_orgs): convert strategic tag to flag
  app/models/student_organization.ts
  database/migrations/1745315804370_add_strategic_flag.ts
  database/migrations/1745315804371_convert_strategic_tag_to_flag.ts
  database/scrapers/organizations.ts
Labels: size/M

#162 feat: add [pl,en] localization
  app/admin/components/dashboard.tsx
  app/admin/components/photo_display.tsx
  app/admin/components/photo_dropbox.tsx
  app/admin/locale.ts
  app/admin/locale/en/translation.json
  app/admin/locale/locale.ts
  app/admin/locale/pl/translation.json
  app/admin/resources/resource_registers/about_us.ts
  app/admin/resources/resource_registers/academic_calendars.ts
  app/admin/resources/resource_registers/admin_panel.ts
  app/admin/resources/resource_registers/buildings.ts
  app/admin/resources/resource_registers/departments.ts
  app/admin/resources/resource_registers/guides.ts
  app/admin/resources/resource_registers/student_organizations.ts
  app/admin/resources/resource_registers/versions.ts
  config/adminjs.ts
  tsconfig.json
Labels: size/XXL

#177 feat: add pink boxes scraper
  assets/pink_boxes.json
  database/scrapers/pink_boxes.ts
Labels: size/L
