Repository Solvro/backend-topwr, pull requests merged in 2025-08, with the labels that each got.

#215 feat: banners
  app/controllers/banners_controller.ts
  app/decorators/typed_model.ts
  app/models/banner.ts
  database/migrations/1753732387000_create_banners_table.ts
  start/routes.ts
Labels: size/L

#222 feat(ci): link reminder
  .github/workflows/pr_automation.yml
Labels: size/S

#216 feat: file cleanup script
  commands/files_cleanup.ts
Labels: size/L

#224 refactor: set fk actions to restrict
  database/migrations/1755532368818_add_restrict_rules_to_relations.ts
Labels: size/M

#226 feat: add branch fields to map objects and student organizations
  app/enums/branch.ts
  app/models/aed.ts
  app/models/bicycle_shower.ts
  app/models/building.ts
  app/models/campus.ts
  app/models/food_spot.ts
  app/models/library.ts
  app/models/pink_box.ts
  app/models/polinka_station.ts
  app/models/student_organization.ts
  database/migrations/1756117136219_add_branch_to_map_objects_and_student_organizations_table.ts
  database/seeders/building_seeder.ts
  database/seeders/organization_seeder.ts
Labels: size/L
