Repository Solvro/backend-topwr, pull requests merged in 2025-01, with the labels that each got.

#72 fix(models): rename typedModel's meta field
  app/decorators/typed_model.ts
  app/scopes/search_helper.ts
Labels: bug

#83 docs: add missing db schemas
  assets/about_us_db_schema.png
  assets/faq_sections_db_schema.png
  assets/multilayerd_map_db_schema.png
Labels: documentation

#77 feat: connect existing models to admin panel
  app/admin/resources/academic_calendars.ts
  app/admin/resources/buildings.ts
  app/admin/resources/change.ts
  app/admin/resources/contributor.ts
  app/admin/resources/department.ts
  app/admin/resources/guide_article.ts
  app/admin/resources/index.ts
  app/admin/resources/utils/user.ts
  app/enums/building_icon.ts
  app/enums/change_type.ts
  app/enums/link_type.ts
  app/enums/organization_source.ts
  app/enums/organization_type.ts
Labels: enhancement

#100 fix: include assets dir in production builds
  adonisrc.ts
  docs/assets/about_us_db_schema.png
  docs/assets/academic_calendar_schema.png
  docs/assets/buildings_db_schema.png
  docs/assets/contributors_and_changelogs_schema.ddb.json
  docs/assets/contributors_and_changelogs_schema.png
  docs/assets/departments_db_schema.jpeg
  docs/assets/faq_sections_db_schema.png
  docs/assets/multilayerd_map_db_schema.png
  docs/assets/student_organizations_db_schema.png
Labels: bug
