Repository Solvro/backend-topwr, pull requests merged in 2025-04, with the labels that each got.

#119 feat(adminPanel): create reset password procedure
  .env.example
  adonisrc.ts
  app/admin/resources/resource_registers/admin_panel.ts
  app/controllers/users_controller.ts
  app/exceptions/base_error.ts
  app/exceptions/handler.ts
  app/exceptions/http_exceptions.ts
  app/mails/reset_password_notification.ts
  app/middleware/sensitive_errors_middleware.ts
  app/models/user.ts
  app/services/reset_password_service.ts
  app/utils/hash.ts
  app/validators/email.ts
  app/validators/password.ts
  app/validators/reset_password_token.ts
  commands/reset_password.ts
  config/limiter.ts
  config/mail.ts
  database/migrations/1744077320344_create_rate_limits_table.ts
  database/migrations/1744177320344_alter_user_reset_token_and_string_to_text.ts
  package-lock.json
  package.json
  start/env.ts
  start/kernel.ts
  start/limiter.ts
  start/routes.ts
Labels: size/XL

#144 refactor(models): make files db objects with relations
  app/admin/resources/resource_factory.ts
  app/admin/resources/resource_registers/buildings.ts
  app/admin/resources/resource_registers/departments.ts
  app/admin/resources/resource_registers/guides.ts
  app/admin/resources/resource_registers/student_organizations.ts
  app/controllers/about_us_controller.ts
  app/controllers/buildings_controller.ts
  app/controllers/campuses_controller.ts
  app/controllers/changes_controller.ts
  app/controllers/contributors_controller.ts
  app/controllers/departments_controller.ts
  app/controllers/files_controller.ts
  app/controllers/guide_articles_controller.ts
  app/controllers/libraries_controller.ts
  app/controllers/milestones_controller.ts
  app/controllers/roles_controller.ts
  app/controllers/student_organizations_controller.ts
  app/controllers/versions_controller.ts
  app/exceptions/file_service_errors.ts
  app/models/about_us_general.ts
  app/models/aed.ts
  app/models/bicycle_shower.ts
  app/models/building.ts
  app/models/campus.ts
  app/models/change_screenshot.ts
  app/models/contributor.ts
  app/models/department.ts
  app/models/file_entry.ts
  app/models/food_spot.ts
  app/models/guide_article.ts
  app/models/library.ts
  app/models/student_organization.ts
  app/models/version_screenshot.ts
  app/services/files_service.ts
  database/migrations/1744546141212_image_field_renames.ts
  database/migrations/1744547615766_establish_file_relations.ts
  database/scrapers/buildings.ts
  database/scrapers/contributors.ts
  database/scrapers/departments.ts
  database/scrapers/faq.ts
  database/scrapers/organizations.ts
  database/seeders/about_us_seeder.ts
  database/seeders/building_seeder.ts
  database/seeders/contributor_and_changelog_seeder.ts
  database/seeders/department_seeder.ts
  database/seeders/organization_seeder.ts
Labels: size/XL

#147 refactor(models): refactor typedModel into typedColumn
  app/decorators/typed_model.ts
  app/models/about_us_general.ts
  app/models/about_us_general_link.ts
  app/models/academic_calendar.ts
  app/models/aed.ts
  app/models/bicycle_shower.ts
  app/models/building.ts
  app/models/campus.ts
  app/models/change.ts
  app/models/change_screenshot.ts
  app/models/contributor.ts
  app/models/contributor_social_link.ts
  app/models/day_swap.ts
  app/models/department.ts
  app/models/department_link.ts
  app/models/field_of_study.ts
  app/models/food_spot.ts
  app/models/guide_article.ts
  app/models/guide_author.ts
  app/models/guide_question.ts
  app/models/holiday.ts
  app/models/library.ts
  app/models/milestone.ts
  app/models/regular_hour.ts
  app/models/role.ts
  app/models/special_hour.ts
  app/models/student_organization.ts
  app/models/student_organization_link.ts
  app/models/student_organization_tag.ts
  app/models/version.ts
  app/models/version_screenshot.ts
Labels: size/XXL

#152 fix(typedColumn): remove inconsistencies
  app/decorators/typed_model.ts
  app/models/regular_hour.ts
  app/models/version.ts
Labels: size/M

#146 feat(auth): add api token auth
  README.md
  app/controllers/auth_controller.ts
  app/controllers/files_controller.ts
  app/exceptions/handler.ts
  app/middleware/auth_middleware.ts
  app/models/user.ts
  app/validators/auth.ts
  config/auth.ts
  database/migrations/1744548839649_create_access_tokens_table.ts
  package-lock.json
  package.json
  start/kernel.ts
  start/routes.ts
Labels: enhancement, size/L

#155 fix(admin panel): date picker timezone
  app/admin/component_loader.ts
  app/admin/components/timezone_datepicker.tsx
  app/admin/resources/resource_factory.ts
Labels: size/L

#163 feat(departments): added link names to departmentLinks
  app/models/department_link.ts
  database/migrations/1744906324595_add_department_link_names_table.ts
  database/scrapers/departments.ts
  database/seeders/department_seeder.ts
Labels: size/S

#153 fix(building): improve geolocation and make digital_guide_mode enum
  app/admin/resources/resource_registers/buildings.ts
  app/enums/digital_guide_mode.ts
  app/models/building.ts
  database/migrations/1744906324596_alter_buildings_table_geolocation.ts
  database/migrations/1744906324597_alter_buildings_table_digital_guide_enum.ts
  database/scrapers/buildings.ts
  database/seeders/building_seeder.ts
Labels: size/L
